/* RM 상담차팅 v0.5: 구조화 저장 + 맞춤법 교정 + 잔디 전송 */
const CHARTING_COLUMNS=Object.freeze([
['record_id','record_id'],['recorded_at','기록일시'],['consultation_date','상담일'],['chart_type','기록구분'],['student_name','학생명'],['age_group','나이대'],['age_raw','나이_원문'],['gender','성별'],['residence_standard','거주지역_표준'],['residence_raw','거주지_원문'],['conversation_tags','대화성향_태그'],['conversation_notes','대화성향_직접기록'],['occupation_group','직업군'],['occupation_raw','직업_원문'],['organization','기관_회사명'],['past_learning_tags','과거학습_태그'],['past_learning_notes','과거학습_추가내용'],['study_abroad_type','어학연수_유학유형'],['study_abroad_notes','어학연수_유학추가'],['travel_frequency','해외여행경험'],['goal_tags','학습목표_태그'],['goal_notes','학습목표_상세'],['phonics_rating','파닉스평가'],['phonics_notes','파닉스메모'],['pronunciation_rating','음소발음평가'],['pronunciation_notes','음소발음메모'],['vocab_rating','어휘테스트평가'],['vocab_words','어휘테스트단어'],['test_prompt','테스트문항'],['student_response','학생실제영어응답'],['fluency_rating','빠른문장구성과발화_평가'],['fluency_notes','빠른문장구성과발화_메모'],['grammar_rating','문법적정확도_평가'],['grammar_notes','문법적정확도_메모'],['word_order_rating','어순_평가'],['word_order_notes','어순_메모'],['expansion_rating','문장확장_평가'],['expansion_notes','문장확장_메모'],['vocab_analysis_rating','기초어휘_평가'],['vocab_analysis_notes','기초어휘_메모'],['class_tags','권장수업_태그'],['method_tags','지도방식_태그'],['strategy_1','수업전략1'],['strategy_2','수업전략2'],['strategy_3','수업전략3'],['strategy_4','수업전략4'],['strategy_5','수업전략5'],['level_code','공식레벨'],['level_template_code','레벨지침코드'],['level_special_notes','레벨특이사항'],['level_final_text','레벨지침_최종원문'],['original_text','작성원문'],['final_text','최종교정본'],['proofread_status','맞춤법교정상태'],['proofread_model','맞춤법교정모델'],['jandi_send_status','잔디전송상태'],['jandi_sent_at','잔디전송일시'],['jandi_response','잔디응답'],['form_version','폼버전'],['last_updated_at','최종수정일시']]);

function handleChartingPost_(payload){
 verifyChartingPassword_(payload.auth_password);
 const action=String(payload.action||'');
 if(action==='charting_health')return jsonOutput_({ok:true,service:'RM_CHARTING',version:APP_VERSION,sheet_ready:Boolean(getSheetOptional_(SHEETS.CHARTING)),jandi_configured:Boolean(PropertiesService.getScriptProperties().getProperty('JANDI_INCOMING_WEBHOOK_URL')),proofread_configured:Boolean(PropertiesService.getScriptProperties().getProperty('OPENAI_API_KEY'))});
 if(action==='charting_proofread'){
  const text=String(payload.text||'').trim();if(!text)throw new Error('CHARTING_TEXT_REQUIRED');
  const result=proofreadChartingText_(text,Array.isArray(payload.protected_segments)?payload.protected_segments:[]);
  appendChartingLog_('',action,'SUCCESS',result.model,'');
  return jsonOutput_({ok:true,corrected_text:result.text,model:result.model});
 }
 if(action==='charting_submit')return submitChartingRecord_(payload);
 if(action==='charting_retry_jandi')return retryChartingJandi_(String(payload.record_id||''));
 throw new Error('UNKNOWN_CHARTING_ACTION');
}
function verifyChartingPassword_(provided){const expected=PropertiesService.getScriptProperties().getProperty('CHARTING_PASSWORD');if(!expected)throw new Error('CONFIG_CHARTING_PASSWORD');if(String(provided||'')!==expected)throw new Error('INVALID_CHARTING_PASSWORD');}
function proofreadChartingText_(text,protectedSegments){
 const props=PropertiesService.getScriptProperties(),apiKey=props.getProperty('OPENAI_API_KEY'),model=props.getProperty('OPENAI_PROOFREAD_MODEL')||props.getProperty('OPENAI_MODEL')||'gpt-5.6-luna';
 if(!apiKey)throw new Error('CONFIG_OPENAI_API_KEY');
 const masked=maskProtectedSegments_(text,protectedSegments);
 const instructions=['당신은 한국어 상담기록의 맞춤법 교정기입니다.','오직 한글 맞춤법, 띄어쓰기, 명백한 오타, 기본 문장부호만 교정하세요.','내용을 요약, 축약, 확장, 재배열하거나 새로운 사실을 추가하지 마세요.','작성자의 말투, 판단, 강한 표현, 섹션 제목, 번호, 줄바꿈 구조를 최대한 유지하세요.','영어 표현은 명백한 키보드 오타가 아닌 한 수정하지 마세요.','<<RM_PROTECTED_숫자>> 표시는 절대 수정·삭제·이동하지 마세요.','결과에는 설명이나 머리말 없이 교정된 전체 본문만 출력하세요.'].join('\n');
 const response=UrlFetchApp.fetch('https://api.openai.com/v1/responses',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+apiKey},payload:JSON.stringify({model:model,store:false,max_output_tokens:8000,input:[{role:'system',content:instructions},{role:'user',content:masked.text}]}),muteHttpExceptions:true});
 const status=response.getResponseCode(),body=response.getContentText();if(status<200||status>=300)throw new Error('OPENAI_HTTP_'+status+': '+body.slice(0,500));
 const output=extractResponseOutputText_(JSON.parse(body)).trim();if(!output)throw new Error('OPENAI_EMPTY_OUTPUT');
 return{text:restoreProtectedSegments_(output,masked.map),model:model};
}
function maskProtectedSegments_(text,segments){let masked=String(text||'');const map=[];(segments||[]).map(v=>String(v||'').trim()).filter(Boolean).sort((a,b)=>b.length-a.length).forEach(segment=>{if(masked.indexOf(segment)<0)return;const token='<<RM_PROTECTED_'+map.length+'>>';masked=masked.split(segment).join(token);map.push([token,segment]);});return{text:masked,map:map};}
function restoreProtectedSegments_(text,map){let restored=String(text||'');(map||[]).forEach(pair=>{if(restored.indexOf(pair[0])<0)throw new Error('PROTECTED_SEGMENT_LOST: '+pair[0]);restored=restored.split(pair[0]).join(pair[1]);});return restored;}
function submitChartingRecord_(payload){
 const record=payload.record||{},originalText=String(payload.original_text||'').trim(),finalText=String(payload.final_text||'').trim();
 if(!record.student_name)throw new Error('CHARTING_STUDENT_NAME_REQUIRED');if(!record.consultation_date)throw new Error('CHARTING_CONSULTATION_DATE_REQUIRED');if(!record.level_code)throw new Error('CHARTING_LEVEL_REQUIRED');if(!finalText)throw new Error('CHARTING_FINAL_TEXT_REQUIRED');
 const lock=LockService.getScriptLock();lock.waitLock(20000);let recordId=String(payload.record_id||'').trim(),row=0;
 try{
  const sheet=ensureChartingSheet_();if(recordId)row=findRowByValue_(SHEETS.CHARTING,1,recordId);if(!recordId)recordId='CHART-'+Utilities.getUuid();
  const now=new Date(),data=Object.assign({},record,{record_id:recordId,recorded_at:row?getExistingChartingValue_(row,'recorded_at')||now:now,original_text:originalText,final_text:finalText,proofread_status:String(payload.proofread_status||'UNKNOWN'),proofread_model:PropertiesService.getScriptProperties().getProperty('OPENAI_PROOFREAD_MODEL')||PropertiesService.getScriptProperties().getProperty('OPENAI_MODEL')||'gpt-5.6-luna',jandi_send_status:'PENDING',jandi_sent_at:'',jandi_response:'',form_version:record.form_version||'0.5-MVP',last_updated_at:now});
  const rowValues=CHARTING_COLUMNS.map(pair=>valueForSheet_(data[pair[0]]));if(row)sheet.getRange(row,1,1,rowValues.length).setValues([rowValues]);else{row=Math.max(sheet.getLastRow()+1,2);sheet.getRange(row,1,1,rowValues.length).setValues([rowValues]);}
 }finally{lock.releaseLock();}
 let jandiSent=false,jandiError='',jandiResponse='';
 try{jandiResponse=sendChartingToJandi_(finalText);jandiSent=true;updateChartingJandiStatus_(row,'SENT',new Date(),jandiResponse);appendChartingLog_(recordId,'charting_submit','SUCCESS','SHEET_AND_JANDI','');}
 catch(error){jandiError=normalizeErrorCode_(error);updateChartingJandiStatus_(row,'FAILED','',jandiError);appendChartingLog_(recordId,'charting_submit','PARTIAL','SHEET_SAVED_JANDI_FAILED',jandiError);}
 return jsonOutput_({ok:true,record_id:recordId,sheet_saved:true,jandi_sent:jandiSent,jandi_error:jandiError});
}
function retryChartingJandi_(recordId){if(!recordId)throw new Error('CHARTING_RECORD_ID_REQUIRED');const row=findRowByValue_(SHEETS.CHARTING,1,recordId);if(!row)throw new Error('CHARTING_RECORD_NOT_FOUND');const finalText=String(getSheet_(SHEETS.CHARTING).getRange(row,chartingColumnIndex_('final_text')).getValue()||'');if(!finalText)throw new Error('CHARTING_FINAL_TEXT_EMPTY');const response=sendChartingToJandi_(finalText);updateChartingJandiStatus_(row,'SENT',new Date(),response);appendChartingLog_(recordId,'charting_retry_jandi','SUCCESS','JANDI_SENT','');return jsonOutput_({ok:true,record_id:recordId,jandi_sent:true});}
function sendChartingToJandi_(text){const webhookUrl=PropertiesService.getScriptProperties().getProperty('JANDI_INCOMING_WEBHOOK_URL');if(!webhookUrl)throw new Error('CONFIG_JANDI_INCOMING_WEBHOOK_URL');const response=UrlFetchApp.fetch(webhookUrl,{method:'post',contentType:'application/json',payload:JSON.stringify({body:text,connectColor:'#BBCBCD'}),muteHttpExceptions:true});const status=response.getResponseCode(),body=response.getContentText();if(status<200||status>=300)throw new Error('JANDI_INCOMING_HTTP_'+status+': '+body.slice(0,500));return body.slice(0,1000);}
function ensureChartingSheet_(){const spreadsheet=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=spreadsheet.getSheetByName(SHEETS.CHARTING);if(!sheet)sheet=spreadsheet.insertSheet(SHEETS.CHARTING);const headers=CHARTING_COLUMNS.map(pair=>pair[1]);if(sheet.getMaxColumns()<headers.length)sheet.insertColumnsAfter(sheet.getMaxColumns(),headers.length-sheet.getMaxColumns());const current=sheet.getRange(1,1,1,headers.length).getValues()[0];if(current.join('\u0001')!==headers.join('\u0001')){sheet.getRange(1,1,1,headers.length).setValues([headers]);sheet.setFrozenRows(1);sheet.getRange(1,1,1,headers.length).setBackground('#545454').setFontColor('#FFFFFF').setFontWeight('bold').setHorizontalAlignment('center');}return sheet;}
function getSheetOptional_(name){return SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(name);}
function ensureChartingLogSheet_(){const spreadsheet=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=spreadsheet.getSheetByName(SHEETS.CHARTING_LOG);if(!sheet){sheet=spreadsheet.insertSheet(SHEETS.CHARTING_LOG);sheet.getRange(1,1,1,6).setValues([['기록일시','record_id','action','status','message','detail']]);sheet.setFrozenRows(1);sheet.getRange(1,1,1,6).setBackground('#545454').setFontColor('#FFFFFF').setFontWeight('bold');}return sheet;}
function appendChartingLog_(recordId,action,status,message,detail){try{ensureChartingLogSheet_().appendRow([new Date(),recordId||'',action||'',status||'',message||'',detail||'']);}catch(ignored){}}
function chartingColumnIndex_(key){for(let i=0;i<CHARTING_COLUMNS.length;i++)if(CHARTING_COLUMNS[i][0]===key)return i+1;throw new Error('UNKNOWN_CHARTING_COLUMN: '+key);}
function getExistingChartingValue_(row,key){if(!row)return'';return getSheet_(SHEETS.CHARTING).getRange(row,chartingColumnIndex_(key)).getValue();}
function updateChartingJandiStatus_(row,status,sentAt,response){const sheet=getSheet_(SHEETS.CHARTING);sheet.getRange(row,chartingColumnIndex_('jandi_send_status')).setValue(status||'');sheet.getRange(row,chartingColumnIndex_('jandi_sent_at')).setValue(sentAt||'');sheet.getRange(row,chartingColumnIndex_('jandi_response')).setValue(response||'');sheet.getRange(row,chartingColumnIndex_('last_updated_at')).setValue(new Date());}
function valueForSheet_(value){return value===null||value===undefined?'':value;}